{
 "title": "EPaxos",
 "time": { "from": "2019-06-17T14:57:58.543Z", "to": "2019-06-17T14:58:26.275Z" },
 "panels": [
  {
   "title": "Replica Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(epaxos_replica_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(epaxos_replica_requests_total[1s])) by (instance)",
     "legendFormat": "Sum ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(epaxos_client_responses_total[1s])",
     "legendFormat": "Response {{instance}}"
    },
    {
     "expr": "sum(rate(epaxos_client_responses_total[1s]))",
     "legendFormat": "Reponse Sum"
    },
    {
     "expr": "rate(fast_multipaxos_client_unpending_responses_total[1s])",
     "legendFormat": "Unpending Response {{instance}}"
    },
    {
     "expr": "sum(rate(epaxos_client_unpending_responses_total[1s]))",
     "legendFormat": "Unpending Reponse Sum"
    }
   ]
  },
  {
   "title": "Replica Command Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(epaxos_replica_executed_commands_total[1s])",
     "legendFormat": "Executed Commands ({{instance}})"
    },
    {
     "expr": "rate(epaxos_replica_executed_noops_total[1s])",
     "legendFormat": "Executed Noops ({{instance}})"
    },
    {
     "expr": "rate(epaxos_replica_repeated_commands_total[1s])",
     "legendFormat": "Repeated Commands ({{instance}})"
    },
    {
     "expr": "rate(epaxos_replica_committed_commands_total[1s])",
     "legendFormat": "Chosen Commands ({{instance}})"
    }
   ]
  },
  {
   "title": "Replica Recovery Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(epaxos_replica_prepare_phases_started_total[1s])",
     "legendFormat": "Prepare Phases Started ({{instance}})"
    }
   ]
  },
  {
   "title": "Replica Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(epaxos_replica_resend_pre_accepts_total[1s])",
     "legendFormat": "Resend PreAccepts {{instance}}"
    },
    {
     "expr": "rate(epaxos_replica_resend_accepts_total[1s])",
     "legendFormat": "Resend Accepts {{instance}}"
    },
    {
     "expr": "rate(epaxos_replica_resend_prepares_total[1s])",
     "legendFormat": "Resend Prepares {{instance}}"
    },
    {
     "expr": "rate(epaxos_replica_default_to_slow_path_total[1s])",
     "legendFormat": "Default to Slow Path {{instance}}"
    }
   ]
  },
  {
   "title": "Client Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(epaxos_client_repropose_total[1s])",
     "legendFormat": "Repropose {{instance}}"
    }
   ]
  },
  {
   "title": "Replica Dependency Sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(epaxos_replica_dependencies_sum[1s]) / rate(epaxos_replica_dependencies_count[1s])",
     "legendFormat": "Average number of dependencies {{instance}}"
    }
   ]
  }
 ]
}