{
 "title": "Faster Paxos",
 "time": { "from": "2020-06-09T17:40:35.227Z", "to": "2020-06-09T17:41:19.328Z" },
 "templating": {
  "list": [
   { "name": "metric", "query": "metrics(.*)" },
   { "name": "job", "query": "label_values(job)" },
   { "name": "function", "query": "rate, avg_over_time" }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "$function($metric{job=~\"$job\"}[1s])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(fasterpaxos_server_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(fasterpaxos_server_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_client_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(fasterpaxos_client_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    }
   ]
  },
  {
   "title": "Server Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(fasterpaxos_server_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(fasterpaxos_server_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_phase2a_had_nothing_got_noop_total[1s])",
     "legendFormat": "Had nothing got noop ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_phase2a_had_nothing_got_command_total[1s])",
     "legendFormat": "Had nothing got command ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_phase2a_had_noop_got_noop_total[1s])",
     "legendFormat": "Had noop got noop ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_phase2a_had_noop_got_command_total[1s])",
     "legendFormat": "Had noop got command ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_phase2a_had_command_got_noop_total[1s])",
     "legendFormat": "Had command got noop ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_phase2a_had_command_got_command_total[1s])",
     "legendFormat": "Had command got command ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fasterpaxos_client_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_client_client_requests_sent_total[1s])",
     "legendFormat": "Requests sent ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_client_replies_received_total[1s])",
     "legendFormat": "Non-stale replies received ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_client_stale_replies_received_total[1s])",
     "legendFormat": "Stale replies received ({{instance}})"
    },
    {
     "expr": "sum(rate(fasterpaxos_client_client_requests_sent_total[1s]))",
     "legendFormat": "Total requests sent"
    },
    {
     "expr": "sum(rate(fasterpaxos_client_replies_received_total[1s]))",
     "legendFormat": "Total non-stale replies received ({{instance}})"
    },
    {
     "expr": "sum(rate(fasterpaxos_client_stale_replies_received_total[1s]))",
     "legendFormat": "Total stale replies received ({{instance}})"
    }
   ]
  },
  {
   "title": "Command Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fasterpaxos_server_executed_unique_commands_total[1s])",
     "legendFormat": "Unique commands executed (({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_executed_duplicate_commands_total[1s])",
     "legendFormat": "Duplicate commands executed (({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_executed_noops_total[1s])",
     "legendFormat": "Noops executed (({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_executed_unique_commands_total[1s]) + rate(fasterpaxos_server_executed_duplicate_commands_total[1s]) + rate(fasterpaxos_server_executed_noops_total[1s])",
     "legendFormat": "Total executed (({{instance}})"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fasterpaxos_client_resend_client_request_total[1s])",
     "legendFormat": "Resend client request ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_resend_phase1as_total[1s])",
     "legendFormat": "Resend Phase1as ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_resend_phase2as_anys_total[1s])",
     "legendFormat": "Resend Phase2a Anys ({{instance}})"
    }
   ]
  },
  {
   "title": "Recovery and Leader Change",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(fasterpaxos_server_recovers_sent_total[1s])",
     "legendFormat": "Recovers sent ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_ignored_recover_total[1s])",
     "legendFormat": "Ignored Recovers ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_leader_changes_total[1s])",
     "legendFormat": "Leader changes ({{instance}})"
    }
   ]
  },
  {
   "title": "Rare Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(fasterpaxos_server_very_stale_client_requests_total[1s])",
     "legendFormat": "Very stale client requests ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_stale_client_requests_total[1s])",
     "legendFormat": "Stale client requests ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_future_client_request_round_total[1s])",
     "legendFormat": "Future client requests ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_pending_client_requests_total[1s])",
     "legendFormat": "Pending client requests ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_same_round_delegate_phase1as_total[1s])",
     "legendFormat": "Same round delegate Phase1a ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_chosen_in_phase1_total[1s])",
     "legendFormat": "Chosen in Phase 1 ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_future_phase2as_total[1s])",
     "legendFormat": "Future Phase2as ({{instance}})"
    },
    {
     "expr": "rate(fasterpaxos_server_stale_round_total[1s])",
     "legendFormat": "Stale round ({{type}}, {{instance}})"
    }
   ]
  }
 ]
}