{
 "title": "Horizontal",
 "time": { "from": "2020-06-18T23:25:31.236Z", "to": "2020-06-18T23:26:36.785Z" },
 "templating": {
  "list": [
   { "name": "metric", "query": "metrics(.*)" },
   { "name": "job", "query": "label_values(job)" },
   { "name": "function", "query": "rate, avg_over_time" }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "$function($metric{job=~\"$job\"}[1s])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(horizontal_batcher_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(horizontal_batcher_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(horizontal_leader_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(horizontal_leader_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(horizontal_proxy_leader_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(horizontal_proxy_leader_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(horizontal_acceptor_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(horizontal_acceptor_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(horizontal_replica_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(horizontal_replica_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(horizontal_proxy_replica_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(horizontal_proxy_replica_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(horizontal_client_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(horizontal_client_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    }
   ]
  },
  {
   "title": "Leader Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(horizontal_leader_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(horizontal_leader_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Acceptor Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(horizontal_acceptor_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(horizontal_acceptor_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Replica Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(horizontal_replica_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(horizontal_replica_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "sum(rate(horizontal_replica_chosen_watermarks_sent_total[1s])) by (instance)",
     "legendFormat": "Chosen watermarks sent ({{instance}})"
    },
    {
     "expr": "sum(rate(horizontal_replica_recovers_sent_total[1s])) by (instance)",
     "legendFormat": "Recovers sent ({{instance}})"
    },
    {
     "expr": "rate(horizontal_replica_deferred_reads_total[1s])",
     "legendFormat": "Deferred reads ({{instance}})"
    },
    {
     "expr": "rate(horizontal_replica_executed_reads_total[1s])",
     "legendFormat": "Executed reads ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(horizontal_client_replies_received_total[1s])",
     "legendFormat": "Good Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(horizontal_client_replies_received_total[1s]))",
     "legendFormat": "Total Good Reponses"
    },
    {
     "expr": "rate(horizontal_client_stale_client_replies_received_total[1s])",
     "legendFormat": "Stale Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(horizontal_client_stale_client_replies_received_total[1s]))",
     "legendFormat": "Total Stale Reponses"
    },
    {
     "expr": "rate(horizontal_client_client_requests_sent_total[1s])",
     "legendFormat": "Requests sent ({{instance}})"
    },
    {
     "expr": "sum(rate(horizontal_client_client_requests_sent_total[1s]))",
     "legendFormat": "Total requests sent"
    },
    {
     "expr": "rate(horizontal_client_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(horizontal_client_requests_total{type=\"ReadReply\"}[1s]))",
     "legendFormat": "Total ReadReply ({{instance}})"
    }
   ]
  },
  {
   "title": "Command Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(horizontal_replica_redundantly_chosen_total[1s])",
     "legendFormat": "Redundantly Chosen (({{instance}})"
    },
    {
     "expr": "rate(horizontal_replica_executed_unique_commands_total[1s])",
     "legendFormat": "Executed unique commands ({{instance}})"
    },
    {
     "expr": "rate(horizontal_replica_executed_duplicate_commands_total[1s])",
     "legendFormat": "Executed duplicate commands ({{instance}})"
    },
    {
     "expr": "rate(horizontal_replica_executed_noops_total[1s])",
     "legendFormat": "Executed noops ({{instance}})"
    },
    {
     "expr": "rate(horizontal_replica_executed_configurations_total[1s])",
     "legendFormat": "Executed configurations ({{instance}})"
    },
    {
     "expr": "rate(horizontal_replica_executed_unique_commands_total[1s]) + \nrate(horizontal_replica_executed_duplicate_commands_total[1s]) + \nrate(horizontal_replica_executed_noops_total[1s]) + \nrate(horizontal_replica_executed_configurations_total[1s])",
     "legendFormat": "Total executed (({{instance}})"
    }
   ]
  },
  {
   "title": "Alpha Overflows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(horizontal_leader_alpha_overflow_total[1s])",
     "legendFormat": "Alpha overflow ({{instance}})"
    },
    {
     "expr": "rate(horizontal_leader_no_chunks_found_total[1s])",
     "legendFormat": "No chunks found ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Changes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(horizontal_leader_become_leader_total[1s])",
     "legendFormat": "Become leader ({{instance}})"
    },
    {
     "expr": "rate(horizontal_leader_stop_being_leader_total[1s])",
     "legendFormat": "Stop being leader ({{instance}})"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(horizontal_leader_resend_phase1as_total[1s])",
     "legendFormat": "Resend Phase1as ({{instance}})"
    },
    {
     "expr": "rate(horizontal_client_resend_client_request_total[1s])",
     "legendFormat": "Resend client requests ({{instance}})"
    }
   ]
  },
  {
   "title": "Rare Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(horizontal_acceptor_phase1_nacks_sent_total[1s])",
     "legendFormat": "Phase 1 nacks sent (({{instance}})"
    },
    {
     "expr": "rate(horizontal_acceptor_phase2_nacks_sent_total[1s])",
     "legendFormat": "Phase 2 nacks (({{instance}})"
    },
    {
     "expr": "rate(horizontal_leader_stale_phase1bs_total[1s])",
     "legendFormat": "Stale Phase1bs (({{instance}})"
    },
    {
     "expr": "rate(horizontal_leader_stale_phase2bs_total[1s])",
     "legendFormat": "Stale Phase2bs (({{instance}})"
    },
    {
     "expr": "rate(horizontal_leader_phase2b_already_chosen_total[1s])",
     "legendFormat": "Phase2b already chosen (({{instance}})"
    },
    {
     "expr": "rate(horizontal_leader_stale_nack_total[1s])",
     "legendFormat": "Stale nacks (({{instance}})"
    },
    {
     "expr": "rate(horizontal_leader_ignored_recover_total[1s])",
     "legendFormat": "Ignored recover (({{instance}})"
    },
    {
     "expr": "rate(horizontal_replica_recovers_sent_total[1s])",
     "legendFormat": "Recovers sent (({{instance}})"
    },
    {
     "expr": "rate(horizontal_replica_failed_recover_total[1s])",
     "legendFormat": "Failed recovers (({{instance}})"
    }
   ]
  }
 ]
}