{
 "title": "MatchmakerMultiPaxos",
 "time": { "from": "2020-02-21T23:17:44.870Z", "to": "2020-02-21T23:19:31.897Z" },
 "templating": {
  "list": [
   { "name": "metric", "query": "metrics(.*)" },
   { "name": "job", "query": "label_values(job)" },
   { "name": "function", "query": "rate, avg_over_time" }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "$function($metric{job=~\"$job\"}[1s])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_leader_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(matchmakermultipaxos_leader_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_acceptor_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(matchmakermultipaxos_acceptor_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_replica_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(matchmakermultipaxos_replica_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_matchmaker_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(matchmakermultipaxos_matchmaker_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_reconfigurer_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(matchmakermultipaxos_reconfigurer_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    }
   ]
  },
  {
   "title": "Leader Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_leader_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(matchmakermultipaxos_leader_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Matchmaker Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_matchmaker_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(matchmakermultipaxos_matchmaker_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Reconfigurer Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_reconf[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(matchmakermultipaxos_reconfigurer_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Acceptor Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_acceptor_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(matchmakermultipaxos_acceptor_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Replica Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_replica_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(matchmakermultipaxos_replica_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "sum(rate(matchmakermultipaxos_replica_chosen_watermarks_sent_total[1s])) by (instance)",
     "legendFormat": "Chosen watermarks sent ({{instance}})"
    },
    {
     "expr": "sum(rate(matchmakermultipaxos_replica_recovers_sent_total[1s])) by (instance)",
     "legendFormat": "Recovers sent ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_client_responses_total[1s])",
     "legendFormat": "Good Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(matchmakermultipaxos_client_responses_total[1s]))",
     "legendFormat": "Total Good Reponses"
    },
    {
     "expr": "rate(matchmakermultipaxos_client_unpending_responses_total[1s])",
     "legendFormat": "Unpending Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(matchmakermultipaxos_client_unpending_responses_total[1s]))",
     "legendFormat": "Total Unpending Reponses"
    },
    {
     "expr": "rate(matchmakermultipaxos_client_requests_total[1s])",
     "legendFormat": "Requests sent ({{instance}})"
    },
    {
     "expr": "sum(rate(matchmakermultipaxos_client_requests_total[1s]))",
     "legendFormat": "Total requests sent"
    }
   ]
  },
  {
   "title": "Command Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_replica_executed_log_entries_total[1s])",
     "legendFormat": "Executed log entries (type={{type}}) ({{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_replica_executed_commands_total[1s])",
     "legendFormat": "Executed commands ({{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_replica_redundantly_chosen_total[1s])",
     "legendFormat": "Redundantly chosen commands ({{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_replica_reduntantly_executed_commands_total[1s])",
     "legendFormat": "Redundantly executed commands ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Changes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_leader_become_i_i_plus_one_leader_total[1s])",
     "legendFormat": "i/i+1 reconfigurations (type={{successful}}) ({{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_leader_gc_done_during_leader_change[1s])",
     "legendFormat": "GC done during leader change ({{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_leader_become_leader_total[1s])",
     "legendFormat": "Become leader ({{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_leader_stop_being_leader_total[1s])",
     "legendFormat": "Stop being leader ({{instance}})"
    }
   ]
  },
  {
   "title": "Reconfiguration Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_leader_reconfiguration_latency_sum{job=~\"$job\"}[1s])\n/ rate(matchmakermultipaxos_leader_reconfiguration_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "Reconfiguration latency (phase={{phase}}) ({{instance}})"
    }
   ]
  },
  {
   "title": "Reconfiguration Sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_leader_previous_number_of_rounds_total[1s])",
     "legendFormat": "Previous number of rounds (n={{n}}) ({{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_leader_phase1_num_entries_sum{job=~\"$job\"}[1s])\n/ rate(matchmakermultipaxos_leader_phase1_num_entries_count{job=~\"$job\"}[1s])",
     "legendFormat": "Phase 1 number of entries ({{instance}})"
    }
   ]
  },
  {
   "title": "Nack Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_acceptor_phase1_nacks_sent_total[1s])",
     "legendFormat": "Phase 1 nacks sent ({{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_acceptor_phase2_nacks_sent_total[1s])",
     "legendFormat": "Phase 2 nacks sent ({{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_matchmaker_nacks_sent_total[1s])",
     "legendFormat": "Matchmaker nacks sent ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_leader_resend_phase1as_total[1s])",
     "legendFormat": "Resend Phase1as ({{instance}})"
    },
    {
     "expr": "rate(matchmakermultipaxos_leader_leader_changes_total[1s])",
     "legendFormat": "Leader changes ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(matchmakermultipaxos_client_resend_client_request_total[1s])",
     "legendFormat": "Resend client request ({{instance}})"
    }
   ]
  }
 ]
}