{
 "title": "MultiPaxos",
 "time": { "from": "2020-03-30T00:00:07.484Z", "to": "2020-03-30T00:00:14.221Z" },
 "templating": {
  "list": [
   { "name": "metric", "query": "metrics(.*)" },
   { "name": "job", "query": "label_values(job)" },
   { "name": "function", "query": "rate, avg_over_time" }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "$function($metric{job=~\"$job\"}[1s])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(multipaxos_batcher_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(multipaxos_batcher_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(multipaxos_leader_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(multipaxos_leader_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(multipaxos_proxy_leader_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(multipaxos_proxy_leader_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(multipaxos_acceptor_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(multipaxos_acceptor_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(multipaxos_replica_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(multipaxos_replica_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(multipaxos_proxy_replica_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(multipaxos_proxy_replica_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(multipaxos_client_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(multipaxos_client_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    }
   ]
  },
  {
   "title": "Batcher Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(multipaxos_batcher_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(multipaxos_batcher_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "rate(multipaxos_batcher_batches_sent_total[1s])",
     "legendFormat": "Batches sent ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(multipaxos_leader_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(multipaxos_leader_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Proxy Leader Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(multipaxos_proxy_leader_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(multipaxos_proxy_leader_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Acceptor Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(multipaxos_acceptor_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(multipaxos_acceptor_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Replica Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(multipaxos_replica_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(multipaxos_replica_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "sum(rate(multipaxos_replica_chosen_watermarks_sent_total[1s])) by (instance)",
     "legendFormat": "Chosen watermarks sent ({{instance}})"
    },
    {
     "expr": "sum(rate(multipaxos_replica_recovers_sent_total[1s])) by (instance)",
     "legendFormat": "Recovers sent ({{instance}})"
    },
    {
     "expr": "rate(multipaxos_replica_deferred_reads_total[1s])",
     "legendFormat": "Deferred reads ({{instance}})"
    },
    {
     "expr": "rate(multipaxos_replica_executed_reads_total[1s])",
     "legendFormat": "Executed reads ({{instance}})"
    }
   ]
  },
  {
   "title": "Proxy Replica Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(multipaxos_proxy_replica_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(multipaxos_proxy_replica_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(multipaxos_client_replies_received_total[1s])",
     "legendFormat": "Good Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(multipaxos_client_replies_received_total[1s]))",
     "legendFormat": "Total Good Reponses"
    },
    {
     "expr": "rate(multipaxos_client_stale_client_replies_received_total[1s])",
     "legendFormat": "Stale Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(multipaxos_client_stale_client_replies_received_total[1s]))",
     "legendFormat": "Total Stale Reponses"
    },
    {
     "expr": "rate(multipaxos_client_client_requests_sent_total[1s])",
     "legendFormat": "Requests sent ({{instance}})"
    },
    {
     "expr": "sum(rate(multipaxos_client_client_requests_sent_total[1s]))",
     "legendFormat": "Total requests sent"
    },
    {
     "expr": "rate(multipaxos_client_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(multipaxos_client_requests_total{type=\"ReadReply\"}[1s]))",
     "legendFormat": "Total ReadReply ({{instance}})"
    }
   ]
  },
  {
   "title": "Command Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(multipaxos_replica_executed_log_entries_total[1s])",
     "legendFormat": "Executed log entries (type={{type}}) ({{instance}})"
    },
    {
     "expr": "rate(multipaxos_replica_executed_commands_total[1s])",
     "legendFormat": "Executed commands ({{instance}})"
    },
    {
     "expr": "rate(multipaxos_replica_redundantly_chosen_total[1s])",
     "legendFormat": "Redundantly chosen commands ({{instance}})"
    },
    {
     "expr": "rate(multipaxos_replica_reduntantly_executed_commands_total[1s])",
     "legendFormat": "Redundantly executed commands ({{instance}})"
    }
   ]
  },
  {
   "title": "Deferred Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(multipaxos_replica_deferred_read_latency_sum[1s])\n/ rate(multipaxos_replica_deferred_read_latency_count[1s])",
     "legendFormat": "Deferred read latency (ms) ({{job}}:{{instance}})"
    }
   ]
  },
  {
   "title": "Leader Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(multipaxos_leader_resend_phase1as_total[1s])",
     "legendFormat": "Resend Phase1as ({{instance}})"
    },
    {
     "expr": "rate(multipaxos_leader_leader_changes_total[1s])",
     "legendFormat": "Leader changes ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(multipaxos_client_resend_client_request_total[1s])",
     "legendFormat": "Resend client request ({{instance}})"
    },
    {
     "expr": "rate(multipaxos_client_resend_max_slot_requests_total[1s])",
     "legendFormat": "Resend MaxSlot request ({{instance}})"
    },
    {
     "expr": "rate(multipaxos_client_resend_read_requests_total[1s])",
     "legendFormat": "Resend Read request ({{instance}})"
    }
   ]
  }
 ]
}