{
 "title": "Scalog",
 "time": { "from": "2021-04-29T23:37:30.701Z", "to": "2021-04-29T23:38:29.332Z" },
 "templating": {
  "list": [
   { "name": "metric", "query": "metrics(.*)" },
   { "name": "job", "query": "label_values(job)" },
   { "name": "function", "query": "rate, avg_over_time" }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "$function($metric{job=~\"$job\"}[1s])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(scalog_server_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(scalog_server_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(scalog_aggregator_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(scalog_aggregator_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(scalog_leader_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(scalog_leader_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(scalog_acceptor_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(scalog_acceptor_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(scalog_replica_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(scalog_replica_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(scalog_client_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(scalog_client_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    }
   ]
  },
  {
   "title": "Server Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(scalog_server_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(scalog_server_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "rate(scalog_server_pushes_sent[1s])",
     "legendFormat": "Pushes sent ({{instance}})"
    },
    {
     "expr": "rate(scalog_server_recovers_sent[1s])",
     "legendFormat": "Recovers sent ({{instance}})"
    },
    {
     "expr": "rate(scalog_server_batch_size_sum{job=~\"$job\"}[1s])\n/ rate(scalog_server_batch_size_count{job=~\"$job\"}[1s])",
     "legendFormat": "Batch size ({{instance}})"
    }
   ]
  },
  {
   "title": "Aggregator Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(scalog_aggregator_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(scalog_aggregator_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "rate(scalog_aggregator_proposals_sent[1s])",
     "legendFormat": "Proposals sent ({{instance}})"
    },
    {
     "expr": "rate(scalog_aggregator_raw_cuts_pruned[1s])",
     "legendFormat": "Raw cuts pruned ({{instance}})"
    },
    {
     "expr": "rate(scalog_aggregator_recovers_sent[1s])",
     "legendFormat": "Recovers sent ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(scalog_leader_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(scalog_leader_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "rate(scalog_leader_stale_phase2bs_total[1s])",
     "legendFormat": "Total stale Phase2bs ({{instance}})"
    },
    {
     "expr": "rate(scalog_leader_phase2b_already_chosen_total[1s])",
     "legendFormat": "Total already chosen Phase2bs ({{instance}})"
    }
   ]
  },
  {
   "title": "Acceptor Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(scalog_acceptor_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(scalog_acceptor_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Replica Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(scalog_replica_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(scalog_replica_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "sum(rate(scalog_replica_recovers_sent_total[1s])) by (instance)",
     "legendFormat": "Recovers sent ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(scalog_client_replies_received_total[1s])",
     "legendFormat": "Good Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(scalog_client_replies_received_total[1s]))",
     "legendFormat": "Total Good Reponses"
    },
    {
     "expr": "rate(scalog_client_stale_client_replies_received_total[1s])",
     "legendFormat": "Stale Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(scalog_client_stale_client_replies_received_total[1s]))",
     "legendFormat": "Total Stale Reponses"
    },
    {
     "expr": "rate(scalog_client_client_requests_sent_total[1s])",
     "legendFormat": "Requests sent ({{instance}})"
    },
    {
     "expr": "sum(rate(scalog_client_client_requests_sent_total[1s]))",
     "legendFormat": "Total requests sent"
    }
   ]
  },
  {
   "title": "Command Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(scalog_replica_executed_commands_total[1s])",
     "legendFormat": "Executed commands ({{instance}})"
    },
    {
     "expr": "rate(scalog_replica_redundantly_chosen_total[1s])",
     "legendFormat": "Redundantly chosen commands ({{instance}})"
    },
    {
     "expr": "rate(scalog_replica_reduntantly_executed_commands_total[1s])",
     "legendFormat": "Redundantly executed commands ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(scalog_leader_resend_phase1as_total[1s])",
     "legendFormat": "Resend Phase1as ({{instance}})"
    },
    {
     "expr": "rate(scalog_leader_leader_changes_total[1s])",
     "legendFormat": "Leader changes ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(scalog_client_resend_client_request_total[1s])",
     "legendFormat": "Resend client request ({{instance}})"
    },
    {
     "expr": "rate(scalog_client_resend_max_slot_requests_total[1s])",
     "legendFormat": "Resend MaxSlot request ({{instance}})"
    },
    {
     "expr": "rate(scalog_client_resend_read_requests_total[1s])",
     "legendFormat": "Resend Read request ({{instance}})"
    }
   ]
  }
 ]
}