{
 "title": "Simple GC BPaxos",
 "time": { "from": "2019-09-13T00:43:54.912Z", "to": "2019-09-13T00:44:43.595Z" },
 "templating": {
  "list": [
   { "name": "metric", "query": "metrics(.*)" },
   { "name": "job", "query": "label_values(job)" },
   { "name": "function", "query": "rate, avg_over_time" }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "$function($metric{job=~\"$job\"}[1s])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_leader_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(simple_gc_bpaxos_leader_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_dep_service_node_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(simple_gc_bpaxos_dep_service_node_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_proposer_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(simple_gc_bpaxos_proposer_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_acceptor_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(simple_gc_bpaxos_acceptor_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_replica_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(simple_gc_bpaxos_replica_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_garbage_collector_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(simple_gc_bpaxos_garbage_collector_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    }
   ]
  },
  {
   "title": "Leader Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_leader_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(simple_gc_bpaxos_leader_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "sum(rate(simple_gc_bpaxos_leader_requests_total{type=\"ClientRequest\"}[1s])) ",
     "legendFormat": "Total ClientRequest"
    },
    {
     "expr": "rate(simple_gc_bpaxos_leader_proposals_sent_total[1s])",
     "legendFormat": "Proposals Sent ({{instance}}) "
    },
    {
     "expr": "sum(rate(simple_gc_bpaxos_leader_proposals_sent_total[1s]))",
     "legendFormat": "Total Proposals Sent"
    }
   ]
  },
  {
   "title": "Dependency Service Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_dep_service_node_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_dep_service_node_snapshots_total[1s])",
     "legendFormat": "Snapshots ({{instance}})"
    }
   ]
  },
  {
   "title": "Proposer Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_proposer_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(simple_gc_bpaxos_proposer_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "sum(rate(simple_gc_bpaxos_proposer_requests_total{type=\"Propose\"}[1s])) ",
     "legendFormat": "Total Proposals"
    },
    {
     "expr": "rate(simple_gc_bpaxos_proposer_chosen_commands_total[1s])",
     "legendFormat": "Commands Chosen ({{instance}}) "
    },
    {
     "expr": "sum(rate(simple_gc_bpaxos_proposer_chosen_commands_total[1s]))",
     "legendFormat": "Total Commands Chosen"
    }
   ]
  },
  {
   "title": "Acceptor Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_acceptor_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(simple_gc_bpaxos_acceptor_requests_total[1s])) by (instance)",
     "legendFormat": "Sum ({{instance}})"
    }
   ]
  },
  {
   "title": "Replica Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_replica_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(simple_gc_bpaxos_replica_requests_total[1s])) by (instance)",
     "legendFormat": "Sum ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_client_responses_total[1s])",
     "legendFormat": "Response {{instance}}"
    },
    {
     "expr": "sum(rate(simple_gc_bpaxos_client_responses_total[1s]))",
     "legendFormat": "Reponses Sum"
    },
    {
     "expr": "rate(simple_gc_bpaxos_client_requests_total[1s])",
     "legendFormat": "Requests Sent ({{instance}})"
    },
    {
     "expr": "sum(rate(simple_gc_bpaxos_client_requests_total[1s]))",
     "legendFormat": "Total Requests Sent"
    },
    {
     "expr": "rate(simple_gc_bpaxos_client_responses_total[1s])",
     "legendFormat": "Good Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(simple_gc_bpaxos_client_responses_total[1s]))",
     "legendFormat": "Total Good Reponses"
    },
    {
     "expr": "rate(simple_gc_bpaxos_client_unpending_responses_total[1s])",
     "legendFormat": "Unpending Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(simple_gc_bpaxos_client_unpending_responses_total[1s]))",
     "legendFormat": "Total Unpending Reponses"
    }
   ]
  },
  {
   "title": "Command Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_replica_executed_commands_total[1s])",
     "legendFormat": "Executed Commands ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_replica_executed_noops_total[1s])",
     "legendFormat": "Executed Noops ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_replica_executed_snapshots_total[1s])",
     "legendFormat": "Executed Snapshots ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_replica_repeated_commands_total[1s])",
     "legendFormat": "Repeated Commands ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_replica_execute_graph_total[1s])",
     "legendFormat": "Execute Graph ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_replica_recover_vertex_timers_sum[1s]) / rate(simple_gc_bpaxos_replica_recover_vertex_timers_count[1s])",
     "legendFormat": "Average recover vertex timers ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_leader_resend_dependency_requests_total[1s])",
     "legendFormat": "Resend Dependency Requests ({{instance}})"
    }
   ]
  },
  {
   "title": "Proposer Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_proposer_resend_phase1a_total[1s])",
     "legendFormat": "Resend Phase1as ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_proposer_resend_phase2a_total[1s])",
     "legendFormat": "Resend Phase2as ({{instance}})"
    }
   ]
  },
  {
   "title": "Replica Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_replica_recover_vertex_total[1s])",
     "legendFormat": "Recover Vertex ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_replica_execute_graph_timer_total[1s])",
     "legendFormat": "Execute Graph Timer ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_replica_recover_vertex_total_sum[1s]) / rate(simple_gc_bpaxos_replica_recover_vertex_total_count[1s])",
     "legendFormat": "Recover Vertex Timers ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_client_repropose_total[1s])",
     "legendFormat": "Repropose ({{instance}})"
    }
   ]
  },
  {
   "title": "Dependency Sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_gc_bpaxos_dep_service_node_dependencies_sum[1s]) / rate(simple_gc_bpaxos_dep_service_node_dependencies_count[1s])",
     "legendFormat": "Average # of deps on Dep Service ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_dep_service_node_uncompacted_dependencies_sum[1s]) / rate(simple_gc_bpaxos_dep_service_node_uncompacted_dependencies_count[1s])",
     "legendFormat": "Average # of uncompacted deps on Dep Service ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_replica_dependencies_sum[1s]) / rate(simple_gc_bpaxos_replica_dependencies_count[1s])",
     "legendFormat": "Average # of deps on Replica ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_replica_uncompacted_dependencies_sum[1s]) / rate(simple_gc_bpaxos_replica_uncompacted_dependencies_count[1s])",
     "legendFormat": "Average # of uncompated deps on Replica ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_replica_dependency_graph_num_vertices[1s])",
     "legendFormat": "Dependency graph # vertices ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_replica_dependency_graph_num_edges[1s])",
     "legendFormat": "Dependency graph # edges ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_dep_service_node_snapshot_dependencies_sum[1s]) / rate(simple_gc_bpaxos_dep_service_node_snapshot_dependencies_count[1s])",
     "legendFormat": "Average # of snapshot deps on Dep Service ({{instance}})"
    },
    {
     "expr": "rate(simple_gc_bpaxos_dep_service_node_uncompacted_snapshot_dependencies_sum[1s]) / rate(simple_gc_bpaxos_dep_service_node_uncompacted_snapshot_dependencies_count[1s])",
     "legendFormat": "Average # of uncompacted snapshot deps on Dep Service ({{instance}})"
    }
   ]
  }
 ]
}