{
 "title": "Simple BPaxos",
 "time": { "from": "2019-06-24T22:10:23.432Z", "to": "2019-06-24T22:10:50.475Z" },
 "panels": [
  {
   "title": "Leader Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(simple_bpaxos_leader_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(simple_bpaxos_leader_requests_total[1s])) by (instance)",
     "legendFormat": "Sum ({{instance}})"
    }
   ]
  },
  {
   "title": "Proposer Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(simple_bpaxos_proposer_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(simple_bpaxos_proposer_requests_total[1s])) by (instance)",
     "legendFormat": "Sum ({{instance}})"
    },
    {
     "expr": "rate(simple_bpaxos_proposer_propose_total[1s])",
     "legendFormat": "Propose ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_bpaxos_client_responses_total[1s])",
     "legendFormat": "Response {{instance}}"
    },
    {
     "expr": "sum(rate(simple_bpaxos_client_responses_total[1s]))",
     "legendFormat": "Reponse Sum"
    },
    {
     "expr": "rate(simple_bpaxos_client_unpending_responses_total[1s])",
     "legendFormat": "Unpending Response {{instance}}"
    },
    {
     "expr": "sum(rate(simple_bpaxos_client_unpending_responses_total[1s]))",
     "legendFormat": "Unpending Reponse Sum"
    }
   ]
  },
  {
   "title": "Dependency Service Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_bpaxos_dep_service_node_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Acceptor Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(simple_bpaxos_acceptor_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(simple_bpaxos_acceptor_requests_total[1s])) by (instance)",
     "legendFormat": "Sum ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Command Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_bpaxos_leader_executed_commands_total[1s])",
     "legendFormat": "Executed Commands ({{instance}})"
    },
    {
     "expr": "rate(simple_bpaxos_leader_executed_noops_total[1s])",
     "legendFormat": "Executed Noops ({{instance}})"
    },
    {
     "expr": "rate(simple_bpaxos_leader_repeated_commands_total[1s])",
     "legendFormat": "Repeated Commands ({{instance}})"
    },
    {
     "expr": "rate(simple_bpaxos_leader_committed_commands_total[1s])",
     "legendFormat": "Chosen Commands ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_bpaxos_leader_resend_dependency_requests_total[1s])",
     "legendFormat": "Resend PreAccepts {{instance}}"
    }
   ]
  },
  {
   "title": "Proposer Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_bpaxos_proposer_resend_phase1a_total[1s])",
     "legendFormat": "Resend Phase1a {{instance}}"
    },
    {
     "expr": "rate(simple_bpaxos_proposer_resend_phase2a_total[1s])",
     "legendFormat": "Resend Phase2a {{instance}}"
    }
   ]
  },
  {
   "title": "Client Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_bpaxos_client_repropose_total[1s])",
     "legendFormat": "Repropose {{instance}}"
    }
   ]
  },
  {
   "title": "Dependency Sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simple_bpaxos_dep_service_node_dependencies_sum[1s]) / rate(simple_bpaxos_dep_service_node_dependencies_count[1s])",
     "legendFormat": "Average # of deps on dep service ({{instance}})"
    },
    {
     "expr": "rate(simple_bpaxos_leader_dependencies_sum[1s]) / rate(simple_bpaxos_leader_dependencies_count[1s])",
     "legendFormat": "Average # of deps on leader ({{instance}})"
    },
    {
     "expr": "rate(simple_bpaxos_leader_dependency_graph_num_vertices[1s])",
     "legendFormat": "Dependency graph # vertices ({{instance}})"
    },
    {
     "expr": "rate(simple_bpaxos_leader_dependency_graph_num_edges[1s])",
     "legendFormat": "Dependency graph # edges ({{instance}})"
    }
   ]
  }
 ]
}