{
 "title": "SPaxos",
 "time": { "from": "2019-11-02T23:24:20.376Z", "to": "2019-11-02T23:24:49.271Z" },
 "templating": {
  "list": [
   { "name": "metric", "query": "metrics(.*)" },
   { "name": "job", "query": "label_values(job)" },
   { "name": "function", "query": "rate, avg_over_time" }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "$function($metric{job=~\"$job\"}[1s])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_batcher_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(spaxosdecouple_batcher_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(spaxosdecouple_leader_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(spaxosdecouple_leader_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(spaxosdecouple_proxy_leader_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(spaxosdecouple_proxy_leader_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(spaxosdecouple_acceptor_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(spaxosdecouple_acceptor_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(spaxosdecouple_replica_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(spaxosdecouple_replica_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(spaxosdecouple_proxy_replica_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(spaxosdecouple_proxy_replica_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(spaxosdecouple_disseminator_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(spaxosdecouple_disseminator_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    },
    {
     "expr": "rate(spaxosdecouple_proposer_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(spaxosdecouple_proposer_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    }
   ]
  },
  {
   "title": "Batcher Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_batcher_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_batcher_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "rate(spaxosdecouple_batcher_batches_sent_total[1s])",
     "legendFormat": "Batches sent ({{instance}})"
    }
   ]
  },
  {
   "title": "Proposer Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_proposer_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_proposer_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Disseminator Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_disseminator_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_disseminator_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_leader_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_leader_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Proxy Leader Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_proxy_leader_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_proxy_leader_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Acceptor Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_acceptor_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_acceptor_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Replica Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_replica_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_replica_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_replica_chosen_watermarks_sent_total[1s])) by (instance)",
     "legendFormat": "Chosen watermarks sent ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_replica_recovers_sent_total[1s])) by (instance)",
     "legendFormat": "Recovers sent ({{instance}})"
    }
   ]
  },
  {
   "title": "Proxy Replica Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_proxy_replica_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_proxy_replica_requests_total[1s])) by (instance)",
     "legendFormat": "Total Inbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_client_responses_total[1s])",
     "legendFormat": "Good Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_client_responses_total[1s]))",
     "legendFormat": "Total Good Reponses"
    },
    {
     "expr": "rate(spaxosdecouple_client_unpending_responses_total[1s])",
     "legendFormat": "Unpending Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_client_unpending_responses_total[1s]))",
     "legendFormat": "Total Unpending Reponses"
    },
    {
     "expr": "rate(spaxosdecouple_client_requests_total[1s])",
     "legendFormat": "Requests sent ({{instance}})"
    },
    {
     "expr": "sum(rate(spaxosdecouple_client_requests_total[1s]))",
     "legendFormat": "Total requests sent"
    }
   ]
  },
  {
   "title": "Command Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_replica_executed_log_entries_total[1s])",
     "legendFormat": "Executed log entries (type={{type}}) ({{instance}})"
    },
    {
     "expr": "rate(spaxosdecouple_replica_executed_commands_total[1s])",
     "legendFormat": "Executed commands ({{instance}})"
    },
    {
     "expr": "rate(spaxosdecouple_replica_redundantly_chosen_total[1s])",
     "legendFormat": "Redundantly chosen commands ({{instance}})"
    },
    {
     "expr": "rate(spaxosdecouple_replica_reduntantly_executed_commands_total[1s])",
     "legendFormat": "Redundantly executed commands ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_leader_resend_phase1as_total[1s])",
     "legendFormat": "Resend Phase1as ({{instance}})"
    },
    {
     "expr": "rate(spaxosdecouple_leader_leader_changes_total[1s])",
     "legendFormat": "Leader changes ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spaxosdecouple_client_resend_client_request_total[1s])",
     "legendFormat": "Resend client request ({{instance}})"
    }
   ]
  }
 ]
}