{
 "title": "Unanimous BPaxos",
 "time": { "from": "2019-06-28T18:39:59.624Z", "to": "2019-06-28T18:40:24.578Z" },
 "panels": [
  {
   "title": "Leader Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(unanimous_bpaxos_leader_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(unanimous_bpaxos_leader_requests_total[1s])) by (instance)",
     "legendFormat": "Sum ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(unanimous_bpaxos_client_responses_total[1s])",
     "legendFormat": "Response {{instance}}"
    },
    {
     "expr": "sum(rate(unanimous_bpaxos_client_responses_total[1s]))",
     "legendFormat": "Reponse Sum"
    },
    {
     "expr": "rate(unanimous_bpaxos_client_unpending_responses_total[1s])",
     "legendFormat": "Unpending Response {{instance}}"
    },
    {
     "expr": "sum(rate(unanimous_bpaxos_client_unpending_responses_total[1s]))",
     "legendFormat": "Unpending Reponse Sum"
    }
   ]
  },
  {
   "title": "Dependency Service Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(unanimous_bpaxos_dep_service_node_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "rate(unanimous_bpaxos_dep_service_node_duplicate_request_total[1s])",
     "legendFormat": "Duplicate Requqests ({{instance}})"
    }
   ]
  },
  {
   "title": "Acceptor Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(unanimous_bpaxos_acceptor_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    },
    {
     "expr": "sum(rate(unanimous_bpaxos_acceptor_requests_total[1s])) by (instance)",
     "legendFormat": "Sum ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Command Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(unanimous_bpaxos_leader_executed_commands_total[1s])",
     "legendFormat": "Executed Commands ({{instance}})"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_executed_noops_total[1s])",
     "legendFormat": "Executed Noops ({{instance}})"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_repeated_commands_total[1s])",
     "legendFormat": "Repeated Commands ({{instance}})"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_committed_commands_total[1s])",
     "legendFormat": "Chosen Commands ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Fast Path Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(unanimous_bpaxos_leader_fast_path_success_total[1s])",
     "legendFormat": "Fast Path Success ({{instance}})"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_fast_path_fail_total[1s])",
     "legendFormat": "Fast Path Fail ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Recovery Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(unanimous_bpaxos_leader_recover_vertex_total[1s])",
     "legendFormat": "Recover vertex ({{instance}})"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_recover_with_no_votes_total[1s])",
     "legendFormat": "Recover with no votes ({{instance}})"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_recover_from_classic_round_total[1s])",
     "legendFormat": "Recover from classic round ({{instance}})"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_recover_command_from_fast_round_total[1s])",
     "legendFormat": "Recover command from fast path ({{instance}})"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_recover_noop_from_fast_round_total[1s])",
     "legendFormat": "Recover noop from fast path ({{instance}})"
    }
   ]
  },
  {
   "title": "Leader Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(unanimous_bpaxos_leader_resend_dependency_requests_total[1s])",
     "legendFormat": "Resend PreAccepts {{instance}}"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_resend_phase1a_total[1s])",
     "legendFormat": "Resend Phase1as {{instance}}"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_resend_phase2a_total[1s])",
     "legendFormat": "Resend Phase2as {{instance}}"
    }
   ]
  },
  {
   "title": "Client Timeout Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(unanimous_bpaxos_client_repropose_total[1s])",
     "legendFormat": "Repropose {{instance}}"
    }
   ]
  },
  {
   "title": "Dependency Sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(unanimous_bpaxos_dep_service_node_dependencies_sum[1s]) / rate(unanimous_bpaxos_dep_service_node_dependencies_count[1s])",
     "legendFormat": "Average # of deps on dep service ({{instance}})"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_dependencies_sum[1s]) / rate(unanimous_bpaxos_leader_dependencies_count[1s])",
     "legendFormat": "Average # of deps on leader ({{instance}})"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_dependency_graph_num_vertices[1s])",
     "legendFormat": "Dependency graph # vertices ({{instance}})"
    },
    {
     "expr": "rate(unanimous_bpaxos_leader_dependency_graph_num_edges[1s])",
     "legendFormat": "Dependency graph # edges ({{instance}})"
    }
   ]
  }
 ]
}