{
 "title": "Unreplicated",
 "time": { "from": "2019-10-12T23:16:31.933Z", "to": "2019-10-12T23:16:53.752Z" },
 "templating": {
  "list": [
   { "name": "metric", "query": "metrics(.*)" },
   { "name": "job", "query": "label_values(job)" },
   { "name": "function", "query": "rate, avg_over_time" }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "$function($metric{job=~\"$job\"}[1s])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(unreplicated_server_requests_latency_sum{job=~\"$job\"}[1s])\n/ rate(unreplicated_server_requests_latency_count{job=~\"$job\"}[1s])",
     "legendFormat": "{{type}} latency (ms) ({{job}}:{{instance}})"
    }
   ]
  },
  {
   "title": "Server Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(unreplicated_server_requests_total[1s])",
     "legendFormat": "{{type}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Request Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(unreplicated_client_responses_total[1s])",
     "legendFormat": "Good Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(unreplicated_client_responses_total[1s]))",
     "legendFormat": "Total Good Reponses"
    },
    {
     "expr": "rate(unreplicated_client_unpending_responses_total[1s])",
     "legendFormat": "Unpending Responses ({{instance}})"
    },
    {
     "expr": "sum(rate(unreplicated_client_unpending_responses_total[1s]))",
     "legendFormat": "Total Unpending Reponses"
    },
    {
     "expr": "rate(unreplicated_client_requests_total[1s])",
     "legendFormat": "Requests sent ({{instance}})"
    },
    {
     "expr": "sum(rate(unreplicated_client_requests_total[1s]))",
     "legendFormat": "Total requests sent"
    }
   ]
  }
 ]
}