f: 1
leaderAddress { host: "localhost" port: 9000 }
leaderAddress { host: "localhost" port: 9100 }
leaderElectionAddress { host: "localhost" port: 9001 }
leaderElectionAddress { host: "localhost" port: 9101 }
leaderHeartbeatAddress { host: "localhost" port: 9002 }
leaderHeartbeatAddress { host: "localhost" port: 9102 }
acceptorAddress { host: "localhost" port: 10000 }
acceptorAddress { host: "localhost" port: 10100 }
acceptorHeartbeatAddress { host: "localhost" port: 10002 }
acceptorHeartbeatAddress { host: "localhost" port: 10102 }
roundSystemType: MIXED_ROUND_ROBIN
