f: 1
proposerAddress { host: "localhost" port: 9001}
proposerAddress { host: "localhost" port: 9002}
acceptorAddress { host: "localhost" port: 9003}
acceptorAddress { host: "localhost" port: 9004}
acceptorAddress { host: "localhost" port: 9005}
